name: Basic Functionality Check

on:
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Set up database and seed data
        working-directory: ./server
        run: export PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1 && npx prisma migrate dev --name init

      - name: Install test dependencies
        working-directory: ./test
        run: npm install

      - name: Start server
        working-directory: ./server
        run: npm run start:dev &

      - name: Wait for server to start
        run: sleep 15

      - name: Health check server
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:3000/workplaces > /dev/null 2>&1; then
              echo "Server is ready!"
              break
            fi
            echo "Waiting for server... ($i/30)"
            sleep 2
          done

      - name: Run basic functionality tests
        working-directory: ./test
        run: npx jest --config ./jest-basic.json
